Remove deprecated and unused nyq arg from scipy.signal.firwin2() calls
The `nyq` optional keyword argument has been superseded by the `fs` arg and
[deprecated in scipy ver
1.0.0](https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.signal.firwin2.html).

It has been removed in SciPy 1.14.0 and now it's causing ITO-Master runtime errors:

```
.../ito_master/modules/utils_data_normalization.py", line 96, in get_eq_matching
    diff_filter = scipy.signal.firwin2(ntaps,
                                       frq/np.max(frq),
                                       diff_eq,
                                       nfreqs=None, window='hamming',
                                       nyq=None, antisymmetric=False)
TypeError: firwin2() got an unexpected keyword argument 'nyq'
```

The argument is optional and shouldn't have been used in
`utils_data_normalization.py` to start with, since we were just explicitly
setting its value to `None` (same as its default value when it existed).